language: python

sudo: required

os:
  - linux

before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get remove --purge postgresql-9.1
  - sudo service postgresql start 9.5

python:
  - "3.5"

services:
  - postgresql
addons:
  postgresql: "9.5"

before_script:
  - psql -U postgres -c "create user cg_test_user password 'secret' createdb;"
  - psql -U postgres -c "create database cg_test_db owner=cg_test_user;"

install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt

script: nosetests -v